### ISSUE TITLE
BUG with SQL build - no photos table build

### ISSUE THREAD

**Issue by vlbee** [fac-13/pett-y#27]
In ```pgcli``` I ran ```\i <your build.sql file>``` and got the error on build.

This happened to Laweks too.  On second run it seemed to work so.... 

![image](https://user-images.githubusercontent.com/32312712/39043552-a39f7e1c-4485-11e8-8733-0d116a095192.png)

**Comment by LawEKS** [comment]
I actually tried to run your `db_build.js` file to build the database, but it did not work.
I also ran your test but it did not work
I made these changes and it fixed these problems:

```jsx
const path = require('path');
const { QueryFile } = require('pg-promise');
const dbConnect = require('./db_connect.js');

const sql = file => QueryFile(path.join(__dirname, file), { minify: true });

let build;

build = sql('./db_build.sql');

// This will be executed when the file is run
dbConnect.query(build)
  .then(res => console.log('built db', res))
  .catch(e => console.error('error', e));

// This function will return the promise that dbConnect.query() returns
const runDbBuild = () => dbConnect.query(build);

//export function for testing
module.exports = runDbBuild;
```
